name: Copy Shared Types to Repos

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy shared-types to api-service
        run: |
          rsync -a --exclude=.github/ $GITHUB_WORKSPACE/ ../api-service/shared-types/

      - name: Copy shared-types to realtime-service
        run: |
          rsync -a --exclude=.github/ $GITHUB_WORKSPACE/ ../realtime-service/shared-types/

      - name: Copy shared-types to web-client
        run: |
          rsync -a --exclude=.github/ $GITHUB_WORKSPACE/ ../web-client/shared-types/

      - name: Commit and push changes
        run: |
          cd ../api-service
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout dev
          git add shared-types/
          git commit -m "Update shared-types from lipy-ai/shared-types"
          git push origin dev

          cd ../realtime-service
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout dev
          git add shared-types/
          git commit -m "Update shared-types from lipy-ai/shared-types"
          git push origin dev

          cd ../web-client
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout dev
          git add shared-types/
          git commit -m "Update shared-types from lipy-ai/shared-types"
          git push origin dev
